
// This file is automatically generated. Do not modify it.
// To update your app's Firebase configuration, update the `project` field in your
// `firebase-tools.json` file and run `npx firebase-frameworks-tools initialize`.
import { initializeApp, getApp, getApps } from 'firebase/app';
import { getAuth, connectAuthEmulator } from 'firebase/auth';
import { getFirestore, connectFirestoreEmulator } from 'firebase/firestore';

// =================================================================================
// PASTE YOUR FIREBASE CONFIG OBJECT HERE
// =================================================================================
// You can get this from the Firebase console for your project:
// Project settings > General > Your apps > Web app > Firebase SDK snippet > Config
const firebaseConfig = {
  apiKey: "AIzaSyCkKw2ox9uBwNeK1P7XX9lguIHhrwboZ-Q",
  authDomain: "sync-tube-musicana.firebaseapp.com",
  projectId: "sync-tube-musicana",
  storageBucket: "sync-tube-musicana.firebasestorage.app",
  messagingSenderId: "451460071166",
  appId: "1:451460071166:web:f8de9fdcff72deb76cefaf",
  measurementId: "G-DMS6R8Z6V0"
};
// =================================================================================
// END OF CONFIG
// =================================================================================


function getFirebaseApp() {
  if (getApps().length) {
    return getApp();
  } else {
    return initializeApp(firebaseConfig);
  }
}

export function getRawFirebaseConfig() {
  return firebaseConfig;
}

// In a production environment, this would not be hardcoded.
const IS_EMULATOR = false;

export function initializeFirebase() {
  const app = getFirebaseApp();
  const auth = getAuth(app);
  const firestore = getFirestore(app);

  if (IS_EMULATOR && process.env.NODE_ENV === 'development') {
    // Repeated calls to connectAuthEmulator with the same arguments are ignored.
    connectAuthEmulator(auth, 'http://127.0.0.1:9099');
    connectFirestoreEmulator(firestore, '127.0.0.1', 8080);
  }

  return { app, auth, firestore };
}
